name: omniedge ppc64le build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      envName:
        description: env of the action
        default: dev
        required: true

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.envName || 'dev' }}
    outputs:
      release_tag: ${{ steps.assemble_artifact.outputs.release_tag }}
    steps:
      - name: Assemble Artifact
        id: assemble_artifact
        env:
          TZ: Asia/Shanghai
        run: |
          if [[ '${{ github.ref_type }}' == 'tag' ]]; then 
            echo "::set-output name=release_tag::${{github.ref_name}}"
          else
            time=$(date +%Y%m%d%H)
            release_tag="$time-${{ env.ENVIRONMENT }}"
            echo "::set-output name=release_tag::$release_tag"
          fi       

  build:
    name: Build on ${{ matrix.os }}
    env:
      ENVIRONMENT: ${{ github.event.inputs.envName || 'dev' }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    needs: create-release
    steps:
      - name: setup env to prod if tag is not empty
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV

      - name: setup env if input env is not empty
        if: ${{ github.event.inputs.env }}
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.env }}" >> $GITHUB_ENV

      - name: Checkout without tag
        if: ${{ !github.event.release.tag_name }}
        uses: actions/checkout@master

      - name: Checkout with tag
        uses: actions/checkout@master
        if: ${{ github.event.release.tag_name }}
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Show CPU Model and Free Space
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'
          free -h

      - name: Show system info
        run: |
          echo -e "system info: $(uname -a)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: omniedge-saas-cli-arm64v8
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ matrix.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/ppc64le
          push: false
          load: true
          file: docker/Dockerfile-ubuntu-ppc64le
          build-args: |
            BUILD_ENV=${{ env.ENVIRONMENT }}
          tags: cli:0.1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: run binfmt
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: run cli
        run: |
          docker run --name omniedge -t -d cli:0.1
      - name: copy file
        run: |
          docker cp omniedge:/app/out/omniedge .
      - name: zip
        run: |
          zip -j ./omniedgecli-ppc64le.zip ./omniedge

      - name: setup prerelease
        run: |
          if [[ '${{ github.ref_type }}' == 'tag' ]]; then
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_HUB_TOKEN }}
          file: ./omniedgecli-ppc64le.zip
          asset_name: omniedgecli-ppc64le.zip
          overwrite: true
          tag: ${{ needs.create-release.outputs.release_tag }}
          prerelease: ${{ env.PRE_RELEASE }}
